// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class Deadline
    {

        /// <summary>
  /// DeadlineForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm DeadlineForm;

        /// <summary>
  /// lstUge8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge8;

        /// <summary>
  /// lstUge7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge7;

        /// <summary>
  /// lstUge6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge6;

        /// <summary>
  /// lstUge5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge5;

        /// <summary>
  /// lstUge4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge4;

        /// <summary>
  /// lstUge3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge3;

        /// <summary>
  /// lstUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge2;

        /// <summary>
  /// lstUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUge1;

        /// <summary>
  /// chkKommerIkke1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke1;

        protected CheckBox chkKommerIkke1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke1 != null)
                {
                    _chkKommerIkke1.CheckedChanged -= chkKommerIkke1_CheckedChanged;
                }

                _chkKommerIkke1 = value;
                if (_chkKommerIkke1 != null)
                {
                    _chkKommerIkke1.CheckedChanged += chkKommerIkke1_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge1;

        /// <summary>
  /// lstOrdreUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge1;

        /// <summary>
  /// lstOrdreTidUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge1;

        /// <summary>
  /// lstMaterialeUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge1;

        /// <summary>
  /// lstMaterialeTidUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge1;

        /// <summary>
  /// chkKommerIkke2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke2;

        protected CheckBox chkKommerIkke2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke2 != null)
                {
                    _chkKommerIkke2.CheckedChanged -= chkKommerIkke2_CheckedChanged;
                }

                _chkKommerIkke2 = value;
                if (_chkKommerIkke2 != null)
                {
                    _chkKommerIkke2.CheckedChanged += chkKommerIkke2_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge2;

        /// <summary>
  /// lstOrdreUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge2;

        /// <summary>
  /// lstOrdreTidUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge2;

        /// <summary>
  /// lstMaterialeUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge2;

        /// <summary>
  /// lstMaterialeTidUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge2;

        /// <summary>
  /// chkKommerIkke3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke3;

        protected CheckBox chkKommerIkke3
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke3;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke3 != null)
                {
                    _chkKommerIkke3.CheckedChanged -= chkKommerIkke3_CheckedChanged;
                }

                _chkKommerIkke3 = value;
                if (_chkKommerIkke3 != null)
                {
                    _chkKommerIkke3.CheckedChanged += chkKommerIkke3_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge3;

        /// <summary>
  /// lstOrdreUge3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge3;

        /// <summary>
  /// lstOrdreTidUge3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge3;

        /// <summary>
  /// lstMaterialeUge3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge3;

        /// <summary>
  /// lstMaterialeTidUge3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge3;

        /// <summary>
  /// chkKommerIkke4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke4;

        protected CheckBox chkKommerIkke4
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke4;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke4 != null)
                {
                    _chkKommerIkke4.CheckedChanged -= chkKommerIkke4_CheckedChanged;
                }

                _chkKommerIkke4 = value;
                if (_chkKommerIkke4 != null)
                {
                    _chkKommerIkke4.CheckedChanged += chkKommerIkke4_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge4;

        /// <summary>
  /// lstOrdreUge4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge4;

        /// <summary>
  /// lstOrdreTidUge4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge4;

        /// <summary>
  /// lstMaterialeUge4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge4;

        /// <summary>
  /// lstMaterialeTidUge4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge4;

        /// <summary>
  /// chkKommerIkke5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke5;

        protected CheckBox chkKommerIkke5
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke5;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke5 != null)
                {
                    _chkKommerIkke5.CheckedChanged -= chkKommerIkke5_CheckedChanged;
                }

                _chkKommerIkke5 = value;
                if (_chkKommerIkke5 != null)
                {
                    _chkKommerIkke5.CheckedChanged += chkKommerIkke5_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge5;

        /// <summary>
  /// lstOrdreUge5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge5;

        /// <summary>
  /// lstOrdreTidUge5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge5;

        /// <summary>
  /// lstMaterialeUge5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge5;

        /// <summary>
  /// lstMaterialeTidUge5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge5;

        /// <summary>
  /// chkKommerIkke6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke6;

        protected CheckBox chkKommerIkke6
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke6;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke6 != null)
                {
                    _chkKommerIkke6.CheckedChanged -= chkKommerIkke6_CheckedChanged;
                }

                _chkKommerIkke6 = value;
                if (_chkKommerIkke6 != null)
                {
                    _chkKommerIkke6.CheckedChanged += chkKommerIkke6_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge6;

        /// <summary>
  /// lstOrdreUge6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge6;

        /// <summary>
  /// lstOrdreTidUge6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge6;

        /// <summary>
  /// lstMaterialeUge6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge6;

        /// <summary>
  /// lstMaterialeTidUge6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge6;

        /// <summary>
  /// chkKommerIkke7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke7;

        protected CheckBox chkKommerIkke7
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke7;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke7 != null)
                {
                    _chkKommerIkke7.CheckedChanged -= chkKommerIkke7_CheckedChanged;
                }

                _chkKommerIkke7 = value;
                if (_chkKommerIkke7 != null)
                {
                    _chkKommerIkke7.CheckedChanged += chkKommerIkke7_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge7;

        /// <summary>
  /// lstOrdreUge7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge7;

        /// <summary>
  /// lstOrdreTidUge7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge7;

        /// <summary>
  /// lstMaterialeUge7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge7;

        /// <summary>
  /// lstMaterialeTidUge7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge7;

        /// <summary>
  /// chkKommerIkke8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private CheckBox _chkKommerIkke8;

        protected CheckBox chkKommerIkke8
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _chkKommerIkke8;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_chkKommerIkke8 != null)
                {
                    _chkKommerIkke8.CheckedChanged -= chkKommerIkke8_CheckedChanged;
                }

                _chkKommerIkke8 = value;
                if (_chkKommerIkke8 != null)
                {
                    _chkKommerIkke8.CheckedChanged += chkKommerIkke8_CheckedChanged;
                }
            }
        }

        /// <summary>
  /// lstUdgivelseUge8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstUdgivelseUge8;

        /// <summary>
  /// lstOrdreUge8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge8;

        /// <summary>
  /// lstOrdreTidUge8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge8;

        /// <summary>
  /// lstMaterialeUge8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge8;

        /// <summary>
  /// lstMaterialeTidUge8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge8;

        /// <summary>
  /// btnOpdater control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnOpdater;

        protected Button btnOpdater
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnOpdater;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click -= btnOpdater_Click;
                }

                _btnOpdater = value;
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click += btnOpdater_Click;
                }
            }
        }
    }
}