// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class Deadline2
    {

        /// <summary>
  /// DeadlineForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm DeadlineForm;

        /// <summary>
  /// lstOrdreUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge1;

        /// <summary>
  /// lstOrdreTidUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge1;

        /// <summary>
  /// lstMaterialeUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge1;

        /// <summary>
  /// lstMaterialeTidUge1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge1;

        /// <summary>
  /// btnOpdater control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnOpdater;

        protected Button btnOpdater
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnOpdater;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click -= btnOpdater_Click;
                }

                _btnOpdater = value;
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click += btnOpdater_Click;
                }
            }
        }

        /// <summary>
  /// lstOrdreUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreUge2;

        /// <summary>
  /// lstOrdreTidUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstOrdreTidUge2;

        /// <summary>
  /// lstMaterialeUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeUge2;

        /// <summary>
  /// lstMaterialeTidUge2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected DropDownList lstMaterialeTidUge2;
    }
}