'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Deadline2

  '''<summary>
  '''DeadlineForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DeadlineForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''lstOrdreUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btnOpdater control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnOpdater As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''lstOrdreUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge2 As Global.System.Web.UI.WebControls.DropDownList
End Class
