'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Deadline

  '''<summary>
  '''DeadlineForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DeadlineForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''lstUge8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge8 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstUge7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge7 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstUge6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge6 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstUge5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge5 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstUge4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge4 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstUge3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge3 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke1 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge1 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke2 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge2 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke3 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge3 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge3 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge3 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge3 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge3 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke4 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge4 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge4 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge4 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge4 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge4 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke5 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge5 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge5 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge5 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge5 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge5 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke6 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge6 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge6 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge6 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge6 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge6 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke7 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge7 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge7 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge7 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge7 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge7 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''chkKommerIkke8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkKommerIkke8 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lstUdgivelseUge8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstUdgivelseUge8 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreUge8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreUge8 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstOrdreTidUge8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstOrdreTidUge8 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeUge8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeUge8 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lstMaterialeTidUge8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstMaterialeTidUge8 As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btnOpdater control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnOpdater As Global.System.Web.UI.WebControls.Button
End Class
