'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Forespoergsel

  '''<summary>
  '''ForeForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ForeForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''txtDLUMmpris control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUMmpris As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnOpdater control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnOpdater As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnFortryd control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnFortryd As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''txtBladMmPris control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladMmPris As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBladMmRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladMmRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBladFarvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladFarvetillæg As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBladFarveRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladFarveRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnÆndringer control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnÆndringer As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''txtDLUMmRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUMmRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtDLUFarveRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUFarveRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtDLUFarvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUFarvetillæg As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btnGodkend control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnGodkend As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''lblBemærkning control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBemærkning As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtBemærkning control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBemærkning As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblBesvaretAf control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBesvaretAf As Global.System.Web.UI.WebControls.Label
End Class
