// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class Forespoergsel
    {

        /// <summary>
  /// ForeForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm ForeForm;

        /// <summary>
  /// txtDLUMmpris control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUMmpris;

        /// <summary>
  /// btnOpdater control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnOpdater;

        protected Button btnOpdater
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnOpdater;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click -= btnOpdater_Click;
                }

                _btnOpdater = value;
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click += btnOpdater_Click;
                }
            }
        }

        /// <summary>
  /// btnFortryd control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnFortryd;

        protected Button btnFortryd
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnFortryd;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnFortryd != null)
                {
                    _btnFortryd.Click -= btnFortryd_Click;
                }

                _btnFortryd = value;
                if (_btnFortryd != null)
                {
                    _btnFortryd.Click += btnFortryd_Click;
                }
            }
        }

        /// <summary>
  /// txtBladMmPris control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladMmPris;

        /// <summary>
  /// txtBladMmRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladMmRabat;

        /// <summary>
  /// txtBladFarvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladFarvetillæg;

        /// <summary>
  /// txtBladFarveRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladFarveRabat;

        /// <summary>
  /// btnÆndringer control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnÆndringer;

        protected Button btnÆndringer
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnÆndringer;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnÆndringer != null)
                {
                    _btnÆndringer.Click -= btnÆndringer_Click;
                }

                _btnÆndringer = value;
                if (_btnÆndringer != null)
                {
                    _btnÆndringer.Click += btnÆndringer_Click;
                }
            }
        }

        /// <summary>
  /// txtDLUMmRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUMmRabat;

        /// <summary>
  /// txtDLUFarveRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUFarveRabat;

        /// <summary>
  /// txtDLUFarvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUFarvetillæg;

        /// <summary>
  /// lblInfo control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblInfo;

        /// <summary>
  /// btnGodkend control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnGodkend;

        protected Button btnGodkend
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnGodkend;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click -= btnGodkend_Click;
                }

                _btnGodkend = value;
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click += btnGodkend_Click;
                }
            }
        }

        /// <summary>
  /// lblBemærkning control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBemærkning;

        /// <summary>
  /// txtBemærkning control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBemærkning;

        /// <summary>
  /// lblBesvaretAf control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBesvaretAf;
    }
}