// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class Forsendelser
    {

        /// <summary>
  /// BemForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm BemForm;

        /// <summary>
  /// txtEmail control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtEmail;

        /// <summary>
  /// txtNavn control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtNavn;

        /// <summary>
  /// btnOpdater control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnOpdater;

        protected Button btnOpdater
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnOpdater;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click -= btnOpdater_Click;
                }

                _btnOpdater = value;
                if (_btnOpdater != null)
                {
                    _btnOpdater.Click += btnOpdater_Click;
                }
            }
        }
    }
}