'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IndtastNavn

  '''<summary>
  '''IndNavnForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents IndNavnForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''txtPersonNavn control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPersonNavn As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnOpdater control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnOpdater As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''validerTxtPersonNavnUdfýldt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents validerTxtPersonNavnUdfýldt As Global.System.Web.UI.WebControls.RequiredFieldValidator
End Class
