'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MainMenu

  '''<summary>
  '''BemForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BemForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''linkPris control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents linkPris As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''linkPrimaer control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents linkPrimaer As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''linkKommuner control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents linkKommuner As Global.System.Web.UI.WebControls.HyperLink
End Class
