'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MmPriser

  '''<summary>
  '''BemForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BemForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''txtTekstside control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTekstside As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSide3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSide3 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSide5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSide5 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSide7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSide7 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtHøjreSide control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHøjreSide As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBolig control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBolig As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtMotorside control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMotorside As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtForlystelser control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtForlystelser As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtStillinger control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtStillinger As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtOfficielle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtOfficielle As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtUddannelse control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtUddannelse As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtRubrik control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtRubrik As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtFarvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtFarvetillæg As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txt4Farvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt4Farvetillæg As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtFarveMin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtFarveMin As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtFarveMax control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtFarveMax As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txt4FarveMin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt4FarveMin As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txt4FarveMax control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txt4FarveMax As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblMin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMin As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblMax control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMax As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtBem control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBem As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnGodkend control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnGodkend As Global.System.Web.UI.WebControls.Button
End Class
