// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class MmPriser2
    {

        /// <summary>
  /// BemForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm BemForm;

        /// <summary>
  /// txtTekstside control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtTekstside;

        /// <summary>
  /// txtStillinger control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtStillinger;

        /// <summary>
  /// btnGodkend control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnGodkend;

        protected Button btnGodkend
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnGodkend;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click -= btnGodkend_Click;
                }

                _btnGodkend = value;
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click += btnGodkend_Click;
                }
            }
        }
    }
}