// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class MmPriser
    {

        /// <summary>
  /// BemForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm BemForm;

        /// <summary>
  /// txtTekstside control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtTekstside;

        /// <summary>
  /// txtSide3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtSide3;

        /// <summary>
  /// txtSide5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtSide5;

        /// <summary>
  /// txtSide7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtSide7;

        /// <summary>
  /// txtHøjreSide control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtHøjreSide;

        /// <summary>
  /// txtBolig control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBolig;

        /// <summary>
  /// txtMotorside control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtMotorside;

        /// <summary>
  /// txtForlystelser control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtForlystelser;

        /// <summary>
  /// txtStillinger control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtStillinger;

        /// <summary>
  /// txtOfficielle control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtOfficielle;

        /// <summary>
  /// txtUddannelse control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtUddannelse;

        /// <summary>
  /// txtRubrik control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtRubrik;

        /// <summary>
  /// txtFarvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtFarvetillæg;

        protected TextBox txtFarvetillæg
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtFarvetillæg;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtFarvetillæg != null)
                {
                    _txtFarvetillæg.TextChanged -= txtFarvetillæg_TextChanged;
                }

                _txtFarvetillæg = value;
                if (_txtFarvetillæg != null)
                {
                    _txtFarvetillæg.TextChanged += txtFarvetillæg_TextChanged;
                }
            }
        }

        /// <summary>
  /// txt4Farvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txt4Farvetillæg;

        protected TextBox txt4Farvetillæg
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt4Farvetillæg;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt4Farvetillæg != null)
                {
                    _txt4Farvetillæg.TextChanged -= txt4Farvetillæg_TextChanged;
                }

                _txt4Farvetillæg = value;
                if (_txt4Farvetillæg != null)
                {
                    _txt4Farvetillæg.TextChanged += txt4Farvetillæg_TextChanged;
                }
            }
        }

        /// <summary>
  /// txtFarveMin control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtFarveMin;

        /// <summary>
  /// txtFarveMax control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtFarveMax;

        /// <summary>
  /// txt4FarveMin control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txt4FarveMin;

        /// <summary>
  /// txt4FarveMax control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txt4FarveMax;

        /// <summary>
  /// lblMin control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblMin;

        /// <summary>
  /// lblMax control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblMax;

        /// <summary>
  /// txtBem control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBem;

        /// <summary>
  /// btnGodkend control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnGodkend;

        protected Button btnGodkend
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnGodkend;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click -= btnGodkend_Click;
                }

                _btnGodkend = value;
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click += btnGodkend_Click;
                }
            }
        }
    }
}