'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OplagClass

  '''<summary>
  '''OrdreForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents OrdreForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''grdPrim control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents grdPrim As Global.System.Web.UI.WebControls.DataGrid

  '''<summary>
  '''txtPostNr control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPostNr As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnAddPostNr control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddPostNr As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''RangeValidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RangeValidator1 As Global.System.Web.UI.WebControls.RangeValidator

  '''<summary>
  '''btnGodkend control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnGodkend As Global.System.Web.UI.WebControls.Button
End Class
