// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class OplagClass
    {

        /// <summary>
  /// OrdreForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm OrdreForm;

        /// <summary>
  /// grdPrim control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private DataGrid _grdPrim;

        protected DataGrid grdPrim
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _grdPrim;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_grdPrim != null)
                {
                    _grdPrim.DeleteCommand -= grdPrim_DeleteCommand;
                    _grdPrim.EditCommand -= grdPrim_EditCommand;
                    _grdPrim.CancelCommand -= grdPrim_CancelCommand;
                    _grdPrim.UpdateCommand -= grdPrim_UpdateCommand;
                }

                _grdPrim = value;
                if (_grdPrim != null)
                {
                    _grdPrim.DeleteCommand += grdPrim_DeleteCommand;
                    _grdPrim.EditCommand += grdPrim_EditCommand;
                    _grdPrim.CancelCommand += grdPrim_CancelCommand;
                    _grdPrim.UpdateCommand += grdPrim_UpdateCommand;
                }
            }
        }

        /// <summary>
  /// txtPostNr control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtPostNr;

        protected TextBox txtPostNr
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtPostNr;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtPostNr != null)
                {
                    _txtPostNr.TextChanged -= txtPostNr_TextChanged;
                }

                _txtPostNr = value;
                if (_txtPostNr != null)
                {
                    _txtPostNr.TextChanged += txtPostNr_TextChanged;
                }
            }
        }

        /// <summary>
  /// btnAddPostNr control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnAddPostNr;

        protected Button btnAddPostNr
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnAddPostNr;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnAddPostNr != null)
                {
                    _btnAddPostNr.Click -= btnAddPostNr_Click;
                }

                _btnAddPostNr = value;
                if (_btnAddPostNr != null)
                {
                    _btnAddPostNr.Click += btnAddPostNr_Click;
                }
            }
        }

        /// <summary>
  /// RangeValidator1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RangeValidator RangeValidator1;

        /// <summary>
  /// btnGodkend control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnGodkend;

        protected Button btnGodkend
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnGodkend;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click -= btnGodkend_Click;
                }

                _btnGodkend = value;
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click += btnGodkend_Click;
                }
            }
        }
    }
}