// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class PF
    {

        /// <summary>
  /// Form1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm Form1;

        /// <summary>
  /// visAntalIndrykn control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label visAntalIndrykn;

        /// <summary>
  /// lblPlacering control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblPlacering;

        /// <summary>
  /// visFarver control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label visFarver;

        /// <summary>
  /// lblFormat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblFormat;

        /// <summary>
  /// visMediebureau control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label visMediebureau;

        /// <summary>
  /// visAnnoncør control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label visAnnoncør;

        /// <summary>
  /// lblMVH control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblMVH;

        /// <summary>
  /// lblAntalIndrykn control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblAntalIndrykn;

        /// <summary>
  /// visPlacering control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label visPlacering;

        /// <summary>
  /// txtBladBemærkning control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladBemærkning;

        /// <summary>
  /// lblFarver control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblFarver;

        /// <summary>
  /// visFormat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label visFormat;

        /// <summary>
  /// lblMediebureau control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblMediebureau;

        /// <summary>
  /// txtDLUMmRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUMmRabat;

        /// <summary>
  /// txtDLUFarvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUFarvetillæg;

        /// <summary>
  /// txtDLUFarveRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUFarveRabat;

        /// <summary>
  /// txtBladMmPris control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladMmPris;

        /// <summary>
  /// txtBladMmRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladMmRabat;

        /// <summary>
  /// txtBladFarvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladFarvetillæg;

        /// <summary>
  /// txtBladFarveRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtBladFarveRabat;

        /// <summary>
  /// lblTilBlad control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblTilBlad;

        /// <summary>
  /// lblBesvaretAf control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBesvaretAf;

        /// <summary>
  /// txtDLUMmpris control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtDLUMmpris;

        /// <summary>
  /// lblAnnoncør control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblAnnoncør;

        /// <summary>
  /// visBemærkning control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox visBemærkning;

        /// <summary>
  /// lblBemærkning control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBemærkning;

        /// <summary>
  /// lblDLUForslag control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblDLUForslag;

        /// <summary>
  /// lblDLUmmPris control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblDLUmmPris;

        /// <summary>
  /// lblDLUmmRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblDLUmmRabat;

        /// <summary>
  /// lblDLUFarvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblDLUFarvetillæg;

        /// <summary>
  /// lblDLUfarverabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblDLUfarverabat;

        /// <summary>
  /// btnGodkend control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnGodkend;

        protected Button btnGodkend
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnGodkend;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click -= btnGodkend_Click;
                }

                _btnGodkend = value;
                if (_btnGodkend != null)
                {
                    _btnGodkend.Click += btnGodkend_Click;
                }
            }
        }

        /// <summary>
  /// btnÆndringer control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnÆndringer;

        protected Button btnÆndringer
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnÆndringer;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnÆndringer != null)
                {
                    _btnÆndringer.Click -= btnÆndringer_Click;
                }

                _btnÆndringer = value;
                if (_btnÆndringer != null)
                {
                    _btnÆndringer.Click += btnÆndringer_Click;
                }
            }
        }

        /// <summary>
  /// lblPlaceringUB control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblPlaceringUB;

        /// <summary>
  /// PlaceringTable control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlTable PlaceringTable;

        /// <summary>
  /// chk357 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected CheckBox chk357;

        /// <summary>
  /// chkHsFm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected CheckBox chkHsFm;

        /// <summary>
  /// chkHøjSide control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected CheckBox chkHøjSide;

        /// <summary>
  /// chkNej control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected CheckBox chkNej;

        /// <summary>
  /// lblÆndring control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblÆndring;

        /// <summary>
  /// lblBladmmpris control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBladmmpris;

        /// <summary>
  /// lblBladmmRabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBladmmRabat;

        /// <summary>
  /// lblBladfarvetillæg control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBladfarvetillæg;

        /// <summary>
  /// lblBladfarverabat control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBladfarverabat;

        /// <summary>
  /// lblBladBemærkning control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblBladBemærkning;

        /// <summary>
  /// lblMarker control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblMarker;
    }
}