'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PF

  '''<summary>
  '''Form1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''visAntalIndrykn control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents visAntalIndrykn As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblPlacering control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPlacering As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''visFarver control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents visFarver As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblFormat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblFormat As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''visMediebureau control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents visMediebureau As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''visAnnoncør control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents visAnnoncør As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblMVH control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMVH As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblAntalIndrykn control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAntalIndrykn As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''visPlacering control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents visPlacering As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtBladBemærkning control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladBemærkning As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblFarver control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblFarver As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''visFormat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents visFormat As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblMediebureau control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMediebureau As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtDLUMmRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUMmRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtDLUFarvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUFarvetillæg As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtDLUFarveRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUFarveRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBladMmPris control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladMmPris As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBladMmRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladMmRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBladFarvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladFarvetillæg As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtBladFarveRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBladFarveRabat As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblTilBlad control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTilBlad As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblBesvaretAf control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBesvaretAf As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtDLUMmpris control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDLUMmpris As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblAnnoncør control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAnnoncør As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''visBemærkning control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents visBemærkning As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblBemærkning control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBemærkning As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblDLUForslag control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblDLUForslag As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblDLUmmPris control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblDLUmmPris As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblDLUmmRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblDLUmmRabat As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblDLUFarvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblDLUFarvetillæg As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblDLUfarverabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblDLUfarverabat As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btnGodkend control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnGodkend As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnÆndringer control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnÆndringer As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''lblPlaceringUB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPlaceringUB As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''PlaceringTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PlaceringTable As Global.System.Web.UI.HtmlControls.HtmlTable

  '''<summary>
  '''chk357 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chk357 As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''chkHsFm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkHsFm As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''chkHøjSide control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkHøjSide As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''chkNej control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkNej As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lblÆndring control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblÆndring As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblBladmmpris control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBladmmpris As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblBladmmRabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBladmmRabat As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblBladfarvetillæg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBladfarvetillæg As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblBladfarverabat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBladfarverabat As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblBladBemærkning control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBladBemærkning As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblMarker control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMarker As Global.System.Web.UI.WebControls.Label
End Class
