// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class SekuKommune
    {

        /// <summary>
  /// OrdreForm control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm OrdreForm;

        /// <summary>
  /// grdPrim control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private DataGrid _grdPrim;

        protected DataGrid grdPrim
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _grdPrim;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_grdPrim != null)
                {
                    _grdPrim.DeleteCommand -= grdPrim_DeleteCommand;
                }

                _grdPrim = value;
                if (_grdPrim != null)
                {
                    _grdPrim.DeleteCommand += grdPrim_DeleteCommand;
                }
            }
        }

        /// <summary>
  /// txtSekuKom control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected TextBox txtSekuKom;

        /// <summary>
  /// btnAddPostNr control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnAddPostNr;

        protected Button btnAddPostNr
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnAddPostNr;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnAddPostNr != null)
                {
                    _btnAddPostNr.Click -= btnAddPostNr_Click;
                }

                _btnAddPostNr = value;
                if (_btnAddPostNr != null)
                {
                    _btnAddPostNr.Click += btnAddPostNr_Click;
                }
            }
        }

        /// <summary>
  /// SekLink control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HyperLink SekLink;

        /// <summary>
  /// RequiredFieldValidator1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RequiredFieldValidator RequiredFieldValidator1;
    }
}