<%@ Page Language="vb" AutoEventWireup="false" Codebehind="SendTilKollega.aspx.vb" Inherits="OrdreApp.SendTilKollega"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<TITLE>Send Til Kollega</TITLE>
		<META content="Microsoft Visual Studio.NET 7.0" name="GENERATOR">
		<META content="Visual Basic 7.0" name="CODE_LANGUAGE">
		<META content="JavaScript" name="vs_defaultClientScript">
		<META content="http://schemas.microsoft.com/intellisense/ie5" name="vs_targetSchema">
		<LINK href="OrdreStyles.css" type="text/css" rel="stylesheet">
	</HEAD>
	<BODY ms_positioning="GridLayout">
		<FORM id="Form1" method="post" runat="server">
			<ASP:LABEL id="lblOverskrift" style="Z-INDEX: 100; LEFT: 16px; POSITION: absolute; TOP: 28px" runat="server" cssclass="SendTilKollega" font-size="X-Large" font-bold="True" height="24px" width="360px">Send til kollega</ASP:LABEL><ASP:LABEL id="lblInfo" style="Z-INDEX: 101; LEFT: 16px; POSITION: absolute; TOP: 76px" runat="server" height="48px" width="440px">Send en mail til de af dine kollegaer, der skal vide besked om dette tilbud.<BR>Hvis du ikke vil sende en mail, tryk på 'Afslut'.</ASP:LABEL><ASP:LABEL id="lblEmail1" style="Z-INDEX: 112; LEFT: 16px; POSITION: absolute; TOP: 150px" runat="server" height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail1" style="Z-INDEX: 108; LEFT: 116px; POSITION: absolute; TOP: 150px" runat="server" height="20px" width="304px" autopostback="True"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx1" style="Z-INDEX: 111; LEFT: 424px; POSITION: absolute; TOP: 150px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail1" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail2" style="Z-INDEX: 113; LEFT: 16px; POSITION: absolute; TOP: 175px" runat="server" height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail2" style="Z-INDEX: 102; LEFT: 116px; POSITION: absolute; TOP: 175px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX>
            <ASP:REGULAREXPRESSIONVALIDATOR id="regEx2" style="Z-INDEX: 110; LEFT: 424px; POSITION: absolute; TOP: 175px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail2" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail3" style="Z-INDEX: 114; LEFT: 16px; POSITION: absolute; TOP: 200px" runat="server" height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail3" style="Z-INDEX: 106; LEFT: 116px; POSITION: absolute; TOP: 200px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx3" style="Z-INDEX: 109; LEFT: 424px; POSITION: absolute; TOP: 200px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail3" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail4" style="Z-INDEX: 115; LEFT: 16px; POSITION: absolute; TOP: 225px" runat="server" height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail4" style="Z-INDEX: 104; LEFT: 116px; POSITION: absolute; TOP: 225px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx4" style="Z-INDEX: 107; LEFT: 424px; POSITION: absolute; TOP: 225px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail4" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail5" style="Z-INDEX: 116; LEFT: 16px; POSITION: absolute; TOP: 250px" runat="server" height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail5" style="Z-INDEX: 103; LEFT: 116px; POSITION: absolute; TOP: 250px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx5" style="Z-INDEX: 105; LEFT: 424px; POSITION: absolute; TOP: 250px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail5" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail6" 
                style="Z-INDEX: 116; LEFT: 16px; POSITION: absolute; TOP: 275px" runat="server" 
                height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail6" style="Z-INDEX: 103; LEFT: 116px; POSITION: absolute; TOP: 275px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx6" style="Z-INDEX: 105; LEFT: 424px; POSITION: absolute; TOP: 275px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail6" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail7" 
                style="Z-INDEX: 116; LEFT: 16px; POSITION: absolute; TOP: 300px" runat="server" 
                height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail7" style="Z-INDEX: 103; LEFT: 116px; POSITION: absolute; TOP: 300px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx7" style="Z-INDEX: 105; LEFT: 424px; POSITION: absolute; TOP: 300px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail7" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail8" 
                style="Z-INDEX: 116; LEFT: 16px; POSITION: absolute; TOP: 325px" runat="server" 
                height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail8" style="Z-INDEX: 103; LEFT: 116px; POSITION: absolute; TOP: 325px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx8" style="Z-INDEX: 105; LEFT: 424px; POSITION: absolute; TOP: 325px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail8" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail9" 
                style="Z-INDEX: 116; LEFT: 16px; POSITION: absolute; TOP: 350px" runat="server" 
                height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail9" style="Z-INDEX: 103; LEFT: 116px; POSITION: absolute; TOP: 350px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx9" style="Z-INDEX: 105; LEFT: 424px; POSITION: absolute; TOP: 350px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail9" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR><ASP:LABEL id="lblEmail10" 
                style="Z-INDEX: 116; LEFT: 16px; POSITION: absolute; TOP: 375px" runat="server" 
                height="20px" width="96px">Indtast email:</ASP:LABEL><ASP:TEXTBOX id="txtEmail10" style="Z-INDEX: 103; LEFT: 116px; POSITION: absolute; TOP: 375px" runat="server" height="20px" width="304px" autopostback="True" enabled="False"></ASP:TEXTBOX><ASP:REGULAREXPRESSIONVALIDATOR id="regEx10" style="Z-INDEX: 105; LEFT: 424px; POSITION: absolute; TOP: 375px" runat="server" height="20px" width="224px" validationexpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" controltovalidate="txtEmail10" errormessage="Forkert indtastet email adresse."></ASP:REGULAREXPRESSIONVALIDATOR>
                <ASP:LABEL id="lblDobbeltklik" 
                style="Z-INDEX: 116; LEFT: 116px; POSITION: absolute; TOP: 410px" runat="server" 
                height="20px" width="96px">Klik 2 gange</ASP:LABEL>
            <ASP:BUTTON id="btnSend" 
              style="Z-INDEX: 117; LEFT: 116px; POSITION: absolute; TOP: 425px" 
              runat="server" width="92px" enabled="False" text="Send"></ASP:BUTTON><ASP:BUTTON id="btnAfslut" 
              style="Z-INDEX: 118; LEFT: 330px; POSITION: absolute; TOP: 425px" 
              runat="server" width="92px" text="Afslut"></ASP:BUTTON>
        </FORM>
	</BODY>
</HTML>
