'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SendTilKollega

  '''<summary>
  '''Form1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''lblOverskrift control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblOverskrift As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblEmail1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail1 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail2 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail3 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail3 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx3 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail4 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail4 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx4 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail5 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail5 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx5 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail6 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail6 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx6 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail7 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail7 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx7 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail8 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail8 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx8 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail9 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail9 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail9 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail9 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx9 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx9 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblEmail10 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail10 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtEmail10 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail10 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regEx10 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regEx10 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''lblDobbeltklik control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblDobbeltklik As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btnSend control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnAfslut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAfslut As Global.System.Web.UI.WebControls.Button
End Class
