// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace OrdreApp
{
    public partial class SendTilKollega
    {

        /// <summary>
  /// Form1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected HtmlForm Form1;

        /// <summary>
  /// lblOverskrift control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblOverskrift;

        /// <summary>
  /// lblInfo control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblInfo;

        /// <summary>
  /// lblEmail1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail1;

        /// <summary>
  /// txtEmail1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail1;

        protected TextBox txtEmail1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail1 != null)
                {
                    _txtEmail1.TextChanged -= txtEmail1_TextChanged;
                }

                _txtEmail1 = value;
                if (_txtEmail1 != null)
                {
                    _txtEmail1.TextChanged += txtEmail1_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx1 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx1;

        /// <summary>
  /// lblEmail2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail2;

        /// <summary>
  /// txtEmail2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail2;

        protected TextBox txtEmail2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail2 != null)
                {
                    _txtEmail2.TextChanged -= txtEmail2_TextChanged;
                }

                _txtEmail2 = value;
                if (_txtEmail2 != null)
                {
                    _txtEmail2.TextChanged += txtEmail2_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx2 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx2;

        /// <summary>
  /// lblEmail3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail3;

        /// <summary>
  /// txtEmail3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail3;

        protected TextBox txtEmail3
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail3;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail3 != null)
                {
                    _txtEmail3.TextChanged -= txtEmail3_TextChanged;
                }

                _txtEmail3 = value;
                if (_txtEmail3 != null)
                {
                    _txtEmail3.TextChanged += txtEmail3_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx3 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx3;

        /// <summary>
  /// lblEmail4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail4;

        /// <summary>
  /// txtEmail4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail4;

        protected TextBox txtEmail4
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail4;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail4 != null)
                {
                    _txtEmail4.TextChanged -= txtEmail4_TextChanged;
                }

                _txtEmail4 = value;
                if (_txtEmail4 != null)
                {
                    _txtEmail4.TextChanged += txtEmail4_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx4 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx4;

        /// <summary>
  /// lblEmail5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail5;

        /// <summary>
  /// txtEmail5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail5;

        protected TextBox txtEmail5
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail5;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail5 != null)
                {
                    _txtEmail5.TextChanged -= txtEmail5_TextChanged;
                }

                _txtEmail5 = value;
                if (_txtEmail5 != null)
                {
                    _txtEmail5.TextChanged += txtEmail5_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx5 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx5;

        /// <summary>
  /// lblEmail6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail6;

        /// <summary>
  /// txtEmail6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail6;

        protected TextBox txtEmail6
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail6;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail6 != null)
                {
                    _txtEmail6.TextChanged -= txtEmail6_TextChanged;
                }

                _txtEmail6 = value;
                if (_txtEmail6 != null)
                {
                    _txtEmail6.TextChanged += txtEmail6_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx6 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx6;

        /// <summary>
  /// lblEmail7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail7;

        /// <summary>
  /// txtEmail7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail7;

        protected TextBox txtEmail7
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail7;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail7 != null)
                {
                    _txtEmail7.TextChanged -= txtEmail7_TextChanged;
                }

                _txtEmail7 = value;
                if (_txtEmail7 != null)
                {
                    _txtEmail7.TextChanged += txtEmail7_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx7 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx7;

        /// <summary>
  /// lblEmail8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail8;

        /// <summary>
  /// txtEmail8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail8;

        protected TextBox txtEmail8
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail8;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail8 != null)
                {
                    _txtEmail8.TextChanged -= txtEmail8_TextChanged;
                }

                _txtEmail8 = value;
                if (_txtEmail8 != null)
                {
                    _txtEmail8.TextChanged += txtEmail8_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx8 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx8;

        /// <summary>
  /// lblEmail9 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail9;

        /// <summary>
  /// txtEmail9 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail9;

        protected TextBox txtEmail9
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail9;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail9 != null)
                {
                    _txtEmail9.TextChanged -= txtEmail9_TextChanged;
                }

                _txtEmail9 = value;
                if (_txtEmail9 != null)
                {
                    _txtEmail9.TextChanged += txtEmail9_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx9 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx9;

        /// <summary>
  /// lblEmail10 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblEmail10;

        /// <summary>
  /// txtEmail10 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private TextBox _txtEmail10;

        protected TextBox txtEmail10
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtEmail10;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtEmail10 != null)
                {
                    _txtEmail10.TextChanged -= txtEmail10_TextChanged;
                }

                _txtEmail10 = value;
                if (_txtEmail10 != null)
                {
                    _txtEmail10.TextChanged += txtEmail10_TextChanged;
                }
            }
        }

        /// <summary>
  /// regEx10 control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected RegularExpressionValidator regEx10;

        /// <summary>
  /// lblDobbeltklik control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        protected Label lblDobbeltklik;

        /// <summary>
  /// btnSend control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnSend;

        protected Button btnSend
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnSend;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnSend != null)
                {
                    _btnSend.Click -= btnSend_Click;
                }

                _btnSend = value;
                if (_btnSend != null)
                {
                    _btnSend.Click += btnSend_Click;
                }
            }
        }

        /// <summary>
  /// btnAfslut control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
        private Button _btnAfslut;

        protected Button btnAfslut
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnAfslut;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnAfslut != null)
                {
                    _btnAfslut.Click -= btnAfslut_Click;
                }

                _btnAfslut = value;
                if (_btnAfslut != null)
                {
                    _btnAfslut.Click += btnAfslut_Click;
                }
            }
        }
    }
}